# Generated by Django 5.1.4 on 2024-12-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_contract_text_contract_signed_by_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit...'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='envelope_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('completed', 'Completed'), ('signed', 'Signed'), ('failed', 'Failed')], default='created', max_length=50),
        ),
    ]
