# Generated by Django 5.1.4 on 2024-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_contract_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_text',
            field=models.TextField(),
        ),
    ]
