# Generated by Django 5.1.4 on 2024-12-21 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contract_contract_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'contract', 'verbose_name_plural': 'contracts'},
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='name_field',
            new_name='contract_name',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_field1',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_field2',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent', 'sent'), ('completed', 'completed'), ('signed', 'signed'), ('failed', 'failed')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
